/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Logica.fBalanceG;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yeseliz
 */
public class BalanceG extends javax.swing.JInternalFrame {

    /**
     * Creates new form BalanceG
     */
    public BalanceG() {
        initComponents();
        setResizable(false); //no se maximice la pantalla
        setTitle("Balance General"); //Título del Frame
        mostrar1("");
        mostrar2("");
    }
    
    void ocultarColumnas() { //ocultar las columnas que no quiero que se muestren
        
        //ACTIVOS
        tablaBG1.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaBG1.getColumnModel().getColumn(0).setMinWidth(0);
        tablaBG1.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        tablaBG1.getColumnModel().getColumn(1).setMaxWidth(0);
        tablaBG1.getColumnModel().getColumn(1).setMinWidth(0);
        tablaBG1.getColumnModel().getColumn(1).setPreferredWidth(0);
        
        tablaBG1.getColumnModel().getColumn(3).setMaxWidth(0);
        tablaBG1.getColumnModel().getColumn(3).setMinWidth(0);
        tablaBG1.getColumnModel().getColumn(3).setPreferredWidth(0);
        
        tablaBG1.getColumnModel().getColumn(5).setMaxWidth(0);
        tablaBG1.getColumnModel().getColumn(5).setMinWidth(0);
        tablaBG1.getColumnModel().getColumn(5).setPreferredWidth(0);
        
        tablaBG1.getColumnModel().getColumn(6).setMaxWidth(0);
        tablaBG1.getColumnModel().getColumn(6).setMinWidth(0);
        tablaBG1.getColumnModel().getColumn(6).setPreferredWidth(0);
        
        tablaBG1.getColumnModel().getColumn(7).setMaxWidth(0);
        tablaBG1.getColumnModel().getColumn(7).setMinWidth(0);
        tablaBG1.getColumnModel().getColumn(7).setPreferredWidth(0);
        
        //PASIVOS Y CAPITAL
        tablaBG2.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaBG2.getColumnModel().getColumn(0).setMinWidth(0);
        tablaBG2.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        tablaBG2.getColumnModel().getColumn(1).setMaxWidth(0);
        tablaBG2.getColumnModel().getColumn(1).setMinWidth(0);
        tablaBG2.getColumnModel().getColumn(1).setPreferredWidth(0);
        
        tablaBG2.getColumnModel().getColumn(3).setMaxWidth(0);
        tablaBG2.getColumnModel().getColumn(3).setMinWidth(0);
        tablaBG2.getColumnModel().getColumn(3).setPreferredWidth(0);
        
        tablaBG2.getColumnModel().getColumn(5).setMaxWidth(0);
        tablaBG2.getColumnModel().getColumn(5).setMinWidth(0);
        tablaBG2.getColumnModel().getColumn(5).setPreferredWidth(0);
        
        tablaBG2.getColumnModel().getColumn(6).setMaxWidth(0);
        tablaBG2.getColumnModel().getColumn(6).setMinWidth(0);
        tablaBG2.getColumnModel().getColumn(6).setPreferredWidth(0);
        
        tablaBG2.getColumnModel().getColumn(7).setMaxWidth(0);
        tablaBG2.getColumnModel().getColumn(7).setMinWidth(0);
        tablaBG2.getColumnModel().getColumn(7).setPreferredWidth(0);
        
         
    }
     

    void mostrar1(String buscar) {
        try {
            DefaultTableModel modelo;
            fBalanceG bg = new fBalanceG();
            modelo = bg.mostrar1(buscar);

            tablaBG1.setModel(modelo);
            ocultarColumnas();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
     
      void mostrar2(String buscar) {
        try {
            DefaultTableModel modelo;
            fBalanceG bg = new fBalanceG();
            modelo = bg.mostrar2(buscar);

            tablaBG2.setModel(modelo);
            ocultarColumnas();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

   

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBG2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtTotalA = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaBG1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtTotalP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 7));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("BALANCE GENERAL");

        tablaBG2.setBackground(new java.awt.Color(204, 204, 204));
        tablaBG2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CUENTA", "SALDO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaBG2);

        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Total de activos: $");

        tablaBG1.setBackground(new java.awt.Color(204, 204, 204));
        tablaBG1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CUENTA", "SALDO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaBG1);

        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Total de participaciones: $");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("\"ASERRADEROS\"");

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(276, 276, 276))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 180, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalA, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalP, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTotalA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtTotalP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 730, 510));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalanceG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalanceG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalanceG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalanceG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BalanceG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tablaBG1;
    private javax.swing.JTable tablaBG2;
    private javax.swing.JTextField txtTotalA;
    private javax.swing.JTextField txtTotalP;
    // End of variables declaration//GEN-END:variables
}
