/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import CosteoPorProcesos.*;
import EstadosFinancieros.*;
import Logica.ImagenFondo;
import help.*;


/**
 *
 * @author Yeseliz
 */
public class CGeneral extends javax.swing.JFrame {

    /**
     * Creates new form CGeneral
     */
    public CGeneral() {
        initComponents();
        inicioCG.setBorder(new ImagenFondo());
        this.setExtendedState(CGeneral.MAXIMIZED_BOTH);
        setTitle("Sistema Contable"); //Título del Frame
        inhabilitar();
        inhabilitarUsuario();
        
      
    }
    
    
    
    void inhabilitarUsuario(){
        menuUsuarios.setEnabled(false);
    }
    
    void habilitarUsuario(){
        menuUsuarios.setEnabled(true);
    }
    
     void inhabilitar() {
  
       
        menuAjuste.setEnabled(false);
        menuEF.setEnabled(false);
        menuEmp.setEnabled(false);
        menuCosteo.setEnabled(false);
        
    }

     public void habilitar() {
        menuAjuste.setEnabled(true);
        menuEF.setEnabled(true);
        menuEmp.setEnabled(true);
        menuCosteo.setEnabled(true);
       
    
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        inicioCG = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        menuIniciarPeriodo = new javax.swing.JMenuItem();
        menuCerrarPeriodo = new javax.swing.JMenuItem();
        MenuCG = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        menuconsultarCatalogo = new javax.swing.JMenuItem();
        menuGestionarC = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menuNuevaT = new javax.swing.JMenuItem();
        menuConsultarT = new javax.swing.JMenuItem();
        menuAjuste = new javax.swing.JMenu();
        menuIngresarA = new javax.swing.JMenuItem();
        menuConsultarA = new javax.swing.JMenuItem();
        menuEF = new javax.swing.JMenu();
        menuBalanceC = new javax.swing.JMenuItem();
        menuEstadosResultado = new javax.swing.JMenuItem();
        menuEstadoCapital = new javax.swing.JMenuItem();
        menuBalanceG = new javax.swing.JMenuItem();
        MenuCC = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        menuConsultarP = new javax.swing.JMenuItem();
        menuGestionarP = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        menuConsultarI = new javax.swing.JMenuItem();
        menuKardex = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuEmp = new javax.swing.JMenu();
        menuPlanilla = new javax.swing.JMenuItem();
        menuCosteo = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        menuConfig = new javax.swing.JMenu();
        menuUsuarios = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicioCG.setBackground(new java.awt.Color(102, 204, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO1.png"))); // NOI18N
        inicioCG.add(jLabel2);
        jLabel2.setBounds(990, 520, 310, 190);

        nombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(204, 204, 204));
        inicioCG.add(nombre);
        nombre.setBounds(30, 20, 210, 30);

        getContentPane().add(inicioCG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 720));

        menuBar.setBackground(new java.awt.Color(0, 102, 102));
        menuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 0));
        menuBar.setForeground(new java.awt.Color(0, 102, 102));

        jMenu4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendary.png"))); // NOI18N
        jMenu4.setText("Período Contable");

        menuIniciarPeriodo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuIniciarPeriodo.setText("Iniciar período contable");
        menuIniciarPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIniciarPeriodoActionPerformed(evt);
            }
        });
        jMenu4.add(menuIniciarPeriodo);

        menuCerrarPeriodo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menuCerrarPeriodo.setText("Cerrar período contable");
        menuCerrarPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarPeriodoActionPerformed(evt);
            }
        });
        jMenu4.add(menuCerrarPeriodo);

        menuBar.add(jMenu4);

        MenuCG.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MenuCG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contageneral1.png"))); // NOI18N
        MenuCG.setText("Contabilidad General");

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cuentas1.png"))); // NOI18N
        jMenu7.setText("Cuentas");

        menuconsultarCatalogo.setText("Consultar Catálogo de Cuentas");
        menuconsultarCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuconsultarCatalogoActionPerformed(evt);
            }
        });
        jMenu7.add(menuconsultarCatalogo);

        menuGestionarC.setText("Gestionar Cuentas");
        menuGestionarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarCActionPerformed(evt);
            }
        });
        jMenu7.add(menuGestionarC);

        MenuCG.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/transacciones1.png"))); // NOI18N
        jMenu8.setText("Transacciones");

        menuNuevaT.setText("Nueva Transacción");
        menuNuevaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevaTActionPerformed(evt);
            }
        });
        jMenu8.add(menuNuevaT);

        menuConsultarT.setText("Consultar Transacciones");
        menuConsultarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarTActionPerformed(evt);
            }
        });
        jMenu8.add(menuConsultarT);

        MenuCG.add(jMenu8);

        menuAjuste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pagos.png"))); // NOI18N
        menuAjuste.setText("Ajustes");

        menuIngresarA.setText("Ingresar Ajuste");
        menuIngresarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresarAActionPerformed(evt);
            }
        });
        menuAjuste.add(menuIngresarA);

        menuConsultarA.setText("Consultar Ajustes");
        menuConsultarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarAActionPerformed(evt);
            }
        });
        menuAjuste.add(menuConsultarA);

        MenuCG.add(menuAjuste);

        menuEF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estados financieros.png"))); // NOI18N
        menuEF.setText("Estados Financieros");

        menuBalanceC.setText("Balance  de Comprobación");
        menuBalanceC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBalanceCActionPerformed(evt);
            }
        });
        menuEF.add(menuBalanceC);

        menuEstadosResultado.setText("Estado de Resultados");
        menuEstadosResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEstadosResultadoActionPerformed(evt);
            }
        });
        menuEF.add(menuEstadosResultado);

        menuEstadoCapital.setText("Estado de Capital");
        menuEstadoCapital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEstadoCapitalActionPerformed(evt);
            }
        });
        menuEF.add(menuEstadoCapital);

        menuBalanceG.setText("Balance General");
        menuBalanceG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBalanceGActionPerformed(evt);
            }
        });
        menuEF.add(menuBalanceG);

        MenuCG.add(menuEF);

        menuBar.add(MenuCG);

        MenuCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contacostos1.png"))); // NOI18N
        MenuCC.setText("Contabilidad de Costos");

        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/articulos1.png"))); // NOI18N
        jMenu12.setText("Productos");

        menuConsultarP.setText("Consultar Producto");
        menuConsultarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarPActionPerformed(evt);
            }
        });
        jMenu12.add(menuConsultarP);

        menuGestionarP.setText("Gestionar Producto");
        menuGestionarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarPActionPerformed(evt);
            }
        });
        jMenu12.add(menuGestionarP);

        MenuCC.add(jMenu12);

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inventario1.png"))); // NOI18N
        jMenu13.setText("Inventario");

        menuConsultarI.setText("Consultar Inventario");
        jMenu13.add(menuConsultarI);

        menuKardex.setText("Kardex");
        menuKardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKardexActionPerformed(evt);
            }
        });
        jMenu13.add(menuKardex);

        MenuCC.add(jMenu13);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inicio.png"))); // NOI18N
        jMenu1.setText("Departamentos");

        jMenuItem1.setText("Desensamble");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Corte y costura");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Ensamblado");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        MenuCC.add(jMenu1);

        menuEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clientes.png"))); // NOI18N
        menuEmp.setText("Empleados");

        menuPlanilla.setText("Planilla de Empleados");
        menuPlanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPlanillaActionPerformed(evt);
            }
        });
        menuEmp.add(menuPlanilla);

        MenuCC.add(menuEmp);

        menuCosteo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dinero.png"))); // NOI18N
        menuCosteo.setText("Costeo");

        jMenuItem6.setText("Materia Prima");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuCosteo.add(jMenuItem6);

        jMenu2.setText("Costos de cada Proceso y Terminado");

        jMenuItem4.setText("Costo del Departamento de Desensamble");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Costo del Departamento de Corte y costutra");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem7.setText("Costo del Departamento de Ensamblado");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        menuCosteo.add(jMenu2);

        MenuCC.add(menuCosteo);

        menuBar.add(MenuCC);

        jMenu6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ayuda.png"))); // NOI18N
        jMenu6.setText("Ayuda");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/signo1.png"))); // NOI18N
        jMenuItem11.setText("Ver Ayuda");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem11);

        menuBar.add(jMenu6);

        menuConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Configuraciones.png"))); // NOI18N
        menuConfig.setText("Configuración");

        menuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trabajadores.png"))); // NOI18N
        menuUsuarios.setText("Usuarios y accesos");
        menuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariosActionPerformed(evt);
            }
        });
        menuConfig.add(menuUsuarios);

        menuBar.add(menuConfig);

        menuSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inicio.png"))); // NOI18N
        menuSalir.setText("Salir");
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalirMouseClicked(evt);
            }
        });
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuBar.add(menuSalir);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuIniciarPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIniciarPeriodoActionPerformed
        //menú período contable
        iniciarPeriodoC pc = new iniciarPeriodoC(); //instancia del frame
        inicioCG.add(pc); //agregar el objeto a la pantalla de inicio
        pc.toFront(); // al frente
        pc.setVisible(true);   
    }//GEN-LAST:event_menuIniciarPeriodoActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
      
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMouseClicked
       // menú salir
        Login m = new Login();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuSalirMouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // menú ayuda
    }//GEN-LAST:event_jMenu6MouseClicked

    private void menuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosActionPerformed
        // menú usuarios y acceso
        Trabajador_usuario user = new Trabajador_usuario();
        inicioCG.add(user);
        user.toFront();
        user.setVisible(true);
        
    }//GEN-LAST:event_menuUsuariosActionPerformed

    private void menuCerrarPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarPeriodoActionPerformed
        // TODO add your handling code here:
       /* cerrarPeriodoC cp = new cerrarPeriodoC();
        inicioCG.add(cp);
        cp.toFront();
        cp.setVisible(true);*/
       habilitar();
        
    }//GEN-LAST:event_menuCerrarPeriodoActionPerformed

    private void menuBalanceCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBalanceCActionPerformed
        // TODO add your handling code here:
        BalanceC bc = new BalanceC();
        inicioCG.add(bc);
        bc.toFront();
        bc.setVisible(true);
    }//GEN-LAST:event_menuBalanceCActionPerformed

    private void menuconsultarCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuconsultarCatalogoActionPerformed
        // TODO add your handling code here:
        Catalogo cat = new Catalogo();
        inicioCG.add(cat);
        cat.toFront();
        cat.setVisible(true);
        
    }//GEN-LAST:event_menuconsultarCatalogoActionPerformed

    private void menuGestionarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarCActionPerformed
        // TODO add your handling code here:
        Cuenta cuenta = new Cuenta();
        inicioCG.add(cuenta);
        cuenta.toFront();
        cuenta.setVisible(true);
    }//GEN-LAST:event_menuGestionarCActionPerformed

    private void menuNuevaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevaTActionPerformed
        // TODO add your handling code here:
        Transaccion t = new Transaccion();
        inicioCG.add(t);
        t.toFront();
        t.setVisible(true);
    }//GEN-LAST:event_menuNuevaTActionPerformed

    private void menuConsultarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarTActionPerformed
        // TODO add your handling code here:
        ConsultarT consult = new ConsultarT();
        inicioCG.add(consult);
        consult.toFront();
        consult.setVisible(true);
    }//GEN-LAST:event_menuConsultarTActionPerformed

    private void menuIngresarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresarAActionPerformed
        // TODO add your handling code here:
        Ajustes a = new Ajustes();
        inicioCG.add(a);
        a.toFront();
        a.setVisible(true);
    }//GEN-LAST:event_menuIngresarAActionPerformed

    private void menuConsultarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarAActionPerformed
        // TODO add your handling code here:
        ConsultarA ca = new ConsultarA();
        inicioCG.add(ca);
        ca.toFront();
        ca.setVisible(true);
    }//GEN-LAST:event_menuConsultarAActionPerformed

    private void menuEstadosResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEstadosResultadoActionPerformed
        // TODO add your handling code here:
        EResultados er = new EResultados();
        inicioCG.add(er);
        er.toFront();
        er.setVisible(true);
    }//GEN-LAST:event_menuEstadosResultadoActionPerformed

    private void menuEstadoCapitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEstadoCapitalActionPerformed
        // TODO add your handling code here:
        EstadoC ec = new EstadoC();
        inicioCG.add(ec);
        ec.toFront();
        ec.setVisible(true);
    }//GEN-LAST:event_menuEstadoCapitalActionPerformed

    private void menuBalanceGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBalanceGActionPerformed
        // TODO add your handling code here:
        BalanceG bg = new BalanceG();
        inicioCG.add(bg);
        bg.toFront();
        bg.setVisible(true);
    }//GEN-LAST:event_menuBalanceGActionPerformed

    private void menuConsultarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarPActionPerformed
        // TODO add your handling code here:
        CProductos cp = new CProductos();
        inicioCG.add(cp);
        cp.toFront();
        cp.setVisible(true);
    }//GEN-LAST:event_menuConsultarPActionPerformed

    private void menuGestionarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarPActionPerformed
        // TODO add your handling code here:
        Productos p = new Productos();
        inicioCG.add(p);
        p.toFront();
        p.setVisible(true);
    }//GEN-LAST:event_menuGestionarPActionPerformed

    private void menuPlanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPlanillaActionPerformed
        // TODO add your handling code here:
        Planillas p = new Planillas();
        inicioCG.add(p);
        p.toFront();
        p.setVisible(true);
        
    }//GEN-LAST:event_menuPlanillaActionPerformed

    private void menuKardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKardexActionPerformed
        // TODO add your handling code here:
        Kardex k = new Kardex();
        inicioCG.add(k);
        k.toFront();
        k.setVisible(true);
    }//GEN-LAST:event_menuKardexActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        DepartamentoDerramadoYTala ta = new DepartamentoDerramadoYTala();
        inicioCG.add(ta);
        ta.toFront();
        ta.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        DepartamentoTroceadoYAserrado t = new DepartamentoTroceadoYAserrado();
        inicioCG.add(t);
        t.toFront();
        t.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        DepartamentoAcabado a = new DepartamentoAcabado();
        inicioCG.add(a);
        a.toFront();
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        CPPDerramadoYTala cppdt = new CPPDerramadoYTala();
        inicioCG.add(cppdt);
        cppdt.toFront();
        cppdt.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        CPPAserrado ase = new CPPAserrado();
         inicioCG.add(ase);
        ase.toFront();
        ase.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        CPPAcabado ac = new CPPAcabado();
         inicioCG.add(ac);
        ac.toFront();
        ac.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        MateriaPrima mat = new MateriaPrima();
        inicioCG.add(mat);
        mat.toFront();
        mat.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        Help help = new Help();
        help.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JMenu MenuCC;
    private static javax.swing.JMenu MenuCG;
    public static javax.swing.JDesktopPane inicioCG;
    private static javax.swing.JLabel jLabel2;
    private static javax.swing.JLayeredPane jLayeredPane1;
    private static javax.swing.JMenu jMenu1;
    private static javax.swing.JMenu jMenu12;
    private static javax.swing.JMenu jMenu13;
    private static javax.swing.JMenu jMenu2;
    private static javax.swing.JMenu jMenu4;
    private static javax.swing.JMenu jMenu6;
    private static javax.swing.JMenu jMenu7;
    private static javax.swing.JMenu jMenu8;
    private static javax.swing.JMenuItem jMenuItem1;
    private static javax.swing.JMenuItem jMenuItem11;
    private static javax.swing.JMenuItem jMenuItem2;
    private static javax.swing.JMenuItem jMenuItem3;
    private static javax.swing.JMenuItem jMenuItem4;
    private static javax.swing.JMenuItem jMenuItem5;
    private static javax.swing.JMenuItem jMenuItem6;
    private static javax.swing.JMenuItem jMenuItem7;
    private static javax.swing.JMenu menuAjuste;
    private static javax.swing.JMenuItem menuBalanceC;
    private static javax.swing.JMenuItem menuBalanceG;
    private static javax.swing.JMenuBar menuBar;
    private static javax.swing.JMenuItem menuCerrarPeriodo;
    public static javax.swing.JMenu menuConfig;
    private static javax.swing.JMenuItem menuConsultarA;
    private static javax.swing.JMenuItem menuConsultarI;
    private static javax.swing.JMenuItem menuConsultarP;
    private static javax.swing.JMenuItem menuConsultarT;
    private static javax.swing.JMenu menuCosteo;
    private static javax.swing.JMenu menuEF;
    private static javax.swing.JMenu menuEmp;
    private static javax.swing.JMenuItem menuEstadoCapital;
    private static javax.swing.JMenuItem menuEstadosResultado;
    private static javax.swing.JMenuItem menuGestionarC;
    private static javax.swing.JMenuItem menuGestionarP;
    private static javax.swing.JMenuItem menuIngresarA;
    private static javax.swing.JMenuItem menuIniciarPeriodo;
    private static javax.swing.JMenuItem menuKardex;
    private static javax.swing.JMenuItem menuNuevaT;
    private static javax.swing.JMenuItem menuPlanilla;
    private static javax.swing.JMenu menuSalir;
    private static javax.swing.JMenuItem menuUsuarios;
    private static javax.swing.JMenuItem menuconsultarCatalogo;
    public static javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables

}
