/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CosteoPorProcesos;

/**
 *
 * @author Yeseliz
 */
public class CIF extends javax.swing.JInternalFrame {
public static final Double combustible= 120.0;
public static final Double depreciacion= 73.30;
public static final Double manMo= 25.0;
public static final Double manMaq= 30.0;
public static final Double manTrans= 120.0;
public static final Double anda=7.0;
public static final Double iss= 24.0;
public static final Double imp= 8.0;
public static final Double sueldos= 1280.00;
public static final Double otros= 100.00;
public static final Double luz= 10.0;
public static final Double alquiler= 350.0;
public static Double saldo;
    /**
     * Creates new form CIF
     */
    public CIF() {
        initComponents();
        calcularCIF();
    }

    public static double sumaTotal(){
        saldo = combustible+depreciacion+manMo+manMaq+manTrans+anda+iss+imp+sueldos+otros+luz+alquiler;
        return saldo;
    }
    
    
    
    public  void calcularCIF(){
        //textField.setText(Integer.toString(valor));
        txtCombustible.setText(Double.toString(combustible));
        txtDepreciacion.setText(Double.toString(depreciacion));
        txtManMob.setText(Double.toString(manMo));
        txtManMaq.setText(Double.toString(manMaq));
        txttransporte.setText(Double.toString(manTrans));
        txtanda.setText(Double.toString(anda));
        txtiss.setText(Double.toString(iss));
        txtimp.setText(Double.toString(imp));
        txtsueldos.setText(Double.toString(sueldos));
        txtOtros.setText(Double.toString(otros));
        jTextField2.setText(Double.toString(luz));
        jTextField1.setText(Double.toString(alquiler));
        saldo = combustible+depreciacion+manMo+manMaq+manTrans+anda+iss+imp+sueldos+otros+luz+alquiler;
        txtTotal.setText(Double.toString(saldo));

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCombustible = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtimp = new javax.swing.JTextField();
        txtiss = new javax.swing.JTextField();
        txtanda = new javax.swing.JTextField();
        txttransporte = new javax.swing.JTextField();
        txtManMaq = new javax.swing.JTextField();
        txtManMob = new javax.swing.JTextField();
        txtsueldos = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtDepreciacion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtOtros = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Costos Indirectos de Fabricación");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 4), "CIF", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Combustible:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 42, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Depreciación:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 73, -1, -1));
        jPanel1.add(txtCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 39, 97, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mantenimiento de Mobiliario:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 99, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mantenimiento de Maquinaria:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 131, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mantenimiento de Equipo de Transporte:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 166, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ANDA");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 204, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ISS:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 235, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Impuestos Municipales:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 266, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Sueldos:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 297, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Otros:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        txtimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtimpActionPerformed(evt);
            }
        });
        jPanel1.add(txtimp, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 263, 97, -1));
        jPanel1.add(txtiss, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 232, 97, -1));
        jPanel1.add(txtanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 201, 97, -1));
        jPanel1.add(txttransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 163, 97, -1));
        jPanel1.add(txtManMaq, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 131, 97, -1));
        jPanel1.add(txtManMob, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 99, 97, -1));
        jPanel1.add(txtsueldos, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 294, 97, -1));

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 97, -1));
        jPanel1.add(txtDepreciacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 70, 97, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));
        jPanel1.add(txtOtros, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 97, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 139, 10));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("$");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Luz electrica :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 100, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Alquiler :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 500, 480));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtimpActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtCombustible;
    private javax.swing.JTextField txtDepreciacion;
    private javax.swing.JTextField txtManMaq;
    private javax.swing.JTextField txtManMob;
    private javax.swing.JTextField txtOtros;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtanda;
    private javax.swing.JTextField txtimp;
    private javax.swing.JTextField txtiss;
    private javax.swing.JTextField txtsueldos;
    private javax.swing.JTextField txttransporte;
    // End of variables declaration//GEN-END:variables
}
