/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CosteoPorProcesos;

import Logica.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Yeseliz
 */
public class CPPAcabado extends javax.swing.JInternalFrame {
private Conexion mysql = new Conexion();
private Connection cn = mysql.conectar();
private String sentenciaSql = "";
    /**
     * Creates new form CPPAcabado
     */
    public CPPAcabado() {
        initComponents();
        llenarComboBoxProducto();
    }
    
    //Unidades equivalentes
    public void unidadesEquivalentes(){
       
      
        
    }

    
     public void llenarComboBoxProducto(){
        String productoTerminado,id;
       try {
           sentenciaSql= "SELECT nombreProducto FROM producto WHERE proceso = 'Ensamblado'";
           Statement statement = this.cn.createStatement();
            ResultSet resultado = statement.executeQuery(sentenciaSql);
                while (resultado.next()) {
                productoTerminado=resultado.getString("nombreProducto");
                
                boxProducto.addItem(productoTerminado);
               
            }
                } 
       catch (SQLException ex) {}
    }//Fin de método llenarCombos.
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        boxProducto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnObtenerCosto1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtvarasTerminadas = new javax.swing.JTextField();
        porcenMP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        porcenMO = new javax.swing.JTextField();
        porcenCIF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtVarasT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCIncurrido = new javax.swing.JTextField();
        txtCUE = new javax.swing.JTextField();
        txtCPT = new javax.swing.JTextField();
        costoUnitario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCPP = new javax.swing.JTextField();
        labelNombreProducto = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true), "ACABADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.add(boxProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 110, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seleccione el producto :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        btnObtenerCosto1.setText("Obtener Costo");
        btnObtenerCosto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerCosto1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnObtenerCosto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 112, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Número de Varas terminadasr:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        jPanel2.add(txtvarasTerminadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 90, -1));
        jPanel2.add(porcenMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 90, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("% de avance en Materia Prima:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("% de avance en Mano de Obra:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("% de avance en CIF:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));
        jPanel2.add(porcenMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 90, -1));
        jPanel2.add(porcenCIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 90, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cantidad de yarda utilizada:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));
        jPanel2.add(txtVarasT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 90, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("%");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("%");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("%");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 349, 318));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(204, 204, 204))); // NOI18N

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("(por vara)");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Costo de Producción Terminada: $");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Costos por Unidad Equivalente de MP: $");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Costos Incurridos: $");

        txtCPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPTActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Costo de Producción en Proceso: $");

        txtCPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPPActionPerformed(evt);
            }
        });

        labelNombreProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNombreProducto.setForeground(new java.awt.Color(0, 204, 204));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Costo Unitario: $");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCIncurrido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCUE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCPP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCPT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costoUnitario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(labelNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(txtCIncurrido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCUE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtCPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(51, 51, 51))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 430, 295));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPTActionPerformed

    private void txtCPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPPActionPerformed

    private void btnObtenerCosto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerCosto1ActionPerformed
        // TODO add your handling code here:

         if(txtVarasT.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Ingrese el número de varas totales");
            txtVarasT.requestFocus();
            return;
         } else if(txtvarasTerminadas.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Ingrese el número de varas terminadas");
            txtvarasTerminadas.requestFocus();
            return;
         } else if(porcenMP.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Ingrese el porcentaje de avance de Materia Prima");
            porcenMP.requestFocus();
            return;
         } else if(porcenMO.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Ingrese el porcentaje de avance de Mano de Obra");
            porcenMO.requestFocus();
            return;
         } else if(porcenCIF.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Ingrese el porcentaje de avance de CIF");
            porcenCIF.requestFocus();
            return;
         }else{
        labelNombreProducto.setText((String) boxProducto.getSelectedItem());
        
        DecimalFormat formateador1 = new DecimalFormat("####.##");
        DecimalFormat formateador4 = new DecimalFormat("####.##");
        
        
        Integer unidadesTotales= Integer.parseInt(txtVarasT.getText());
        Integer unidadesTerminadas = Integer.parseInt(txtvarasTerminadas.getText());
        Double avanceMP = Double.parseDouble(porcenMP.getText());
        Double avanceMO = Double.parseDouble(porcenMO.getText());
        Double avanceCIF = Double.parseDouble(porcenCIF.getText());
        
        Integer unidadesProceso = unidadesTotales - unidadesTerminadas;
        
        Double unidadesEquivalenteMP = unidadesProceso*avanceMP/100;
        Double unidadesEquivalenteMO = unidadesProceso*avanceMO/100;
        Double unidadesEquivalenteCIF = unidadesProceso*avanceCIF/100;
        
        Double pt1= unidadesTerminadas+unidadesEquivalenteMP;
        Double pt2= unidadesTerminadas+unidadesEquivalenteMO;
        Double pt3= unidadesTerminadas+unidadesEquivalenteCIF;
        
        Double costosIncurridos = CPPAserrado.Total();
        txtCIncurrido.setText(Double.toString(costosIncurridos));
        
        Double costoUE1= 152/pt1;
        Double costoUE2= 892/pt2;
        Double costoUE3= 2412.24/pt3;
        
        Double sumaCostosUE= costoUE1+costoUE2+costoUE3;
        String convertido1 = formateador1.format(sumaCostosUE);
        Double total1 = Double.parseDouble(convertido1);
        txtCUE.setText(Double.toString(total1));
        
        Double costoPP1= costoUE1*unidadesEquivalenteMP;
        Double costoPP2= costoUE2*unidadesEquivalenteMO;
        Double costoPP3= costoUE3*unidadesEquivalenteCIF;
        
        Double sumaCostosPP = costoPP1+costoPP2+costoPP3;
        String convertido2 = formateador1.format(sumaCostosPP);
        Double total2 = Double.parseDouble(convertido2);
        txtCPP.setText(Double.toString(total2));
    
        Double costoPT1= 152-costoPP1;
        Double costoPT2= 892-costoPP2;
        Double costoPT3= 2412.24-costoPP3;
        
        Double sumaCostosPT= costoPT1+costoPT2+costoPT3;
        String convertido3 = formateador1.format(sumaCostosPT);
        Double total3 = Double.parseDouble(convertido3);
        txtCPT.setText(Double.toString(total3));
        
        //costo Unitario del producto
        Double costoU= total3/unidadesTerminadas;
        String convertido4 = formateador4.format(costoU);
        Double total4 = Double.parseDouble(convertido4);
        costoUnitario.setText(Double.toString(total4));
         }
    }//GEN-LAST:event_btnObtenerCosto1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxProducto;
    private javax.swing.JButton btnObtenerCosto1;
    private javax.swing.JTextField costoUnitario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelNombreProducto;
    private javax.swing.JTextField porcenCIF;
    private javax.swing.JTextField porcenMO;
    private javax.swing.JTextField porcenMP;
    private javax.swing.JTextField txtCIncurrido;
    private javax.swing.JTextField txtCPP;
    private javax.swing.JTextField txtCPT;
    private javax.swing.JTextField txtCUE;
    private javax.swing.JTextField txtVarasT;
    private javax.swing.JTextField txtvarasTerminadas;
    // End of variables declaration//GEN-END:variables
}
